"""Absolute paths to prep data. Never copy these files into the repo."""

from __future__ import annotations

from pathlib import Path

PREP = Path.home() / "datathon_prep"

# Commute (Function 1)
OSM_PBF = PREP / "osm" / "switzerland-latest.osm.pbf"
# Prefer the taxi-stripped clean zip if present (R5 rejects route_type=1500).
# Generated by scripts/clean_gtfs.sh.
_GTFS_RAW = PREP / "gtfs" / "ch_gtfs_2026_latest.zip"
_GTFS_CLEAN = PREP / "gtfs" / "clean" / "ch_gtfs_2026_no_taxi.zip"
GTFS_ZIP = _GTFS_CLEAN if _GTFS_CLEAN.exists() else _GTFS_RAW
GTFS_STOPS_TXT = PREP / "gtfs" / "unzipped" / "stops.txt"

# Amenities (Function 2)
POIS_PARQUET = PREP / "processed" / "ch_pois.parquet"
GREEN_WATER_PARQUET = PREP / "processed" / "ch_green_water.parquet"


def require(path: Path) -> Path:
    if not path.exists():
        raise FileNotFoundError(
            f"Required prep data missing: {path}. "
            f"See prep_data_pointer.md — this file should live under ~/datathon_prep/."
        )
    return path
